//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encuestas
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuestasEncuestas
    {
        public int idRespuesta { get; set; }
        public string respuesta { get; set; }
        public int idPregunta { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual detalleEncuestas detalleEncuestas { get; set; }
    }
}
